-- Seed Categories if empty
INSERT OR IGNORE INTO categories (name, color_bg, color_fg, default_sections) VALUES 
('UGI', '#ccfbf1', '#0d9488', '[{"title":"Esophagus","content":""},{"title":"Stomach","content":""},{"title":"Duodenal Cap","content":""},{"title":"IInd Part of Duodenum","content":""},{"title":"Impression","content":"","highlight":true}]'),
('VLS', '#ede9fe', '#7c3aed', '[{"title":"Vocal Cords","content":""},{"title":"Impression","content":"","highlight":true}]'),
('SIGMOIDOSCOPY', '#fef3c7', '#b45309', '[{"title":"Rectum","content":""},{"title":"Sigmoid Colon","content":""},{"title":"Impression","content":"","highlight":true}]'),
('COLONOSCOPY', '#dbeafe', '#2563eb', '[{"title":"Rectum","content":""},{"title":"Colon","content":""},{"title":"Caecum","content":""},{"title":"Impression","content":"","highlight":true}]'),
('ERCP', '#fee2e2', '#dc2626', '[{"title":"Papilla","content":""},{"title":"CBD","content":""},{"title":"Impression","content":"","highlight":true}]'),
('ENTEROSCOPY', '#fce7f3', '#be185d', '[{"title":"Jejunum","content":""},{"title":"Impression","content":"","highlight":true}]');

-- Seed 37 Clinic Templates
INSERT OR IGNORE INTO templates (name, category, sections) VALUES
('Achalasia Cardia', 'UGI', '[{"title":"Stomach","content":"Normal"},{"title":"Esophagus","content":"Dilated with tertiary contractions+\nResistance at GE junction\nScope negotiable with slight difficulty"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal","highlight":false},{"title":"Advanced Imaging","content":"NBI screening done","highlight":true},{"title":"Impression","content":"Dilated tortuous esophagus with tertiary contractions – ?Achalasia Cardia","highlight":true}]'),
('Atrophic Gastritis', 'UGI', '[{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Pale, thin, marble-like mucosa in gastric fundus & body with erosions in fundus"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Advanced Imaging","content":"NBI screening done","highlight":true},{"title":"Impression","content":"Atrophic gastritis with erosions in gastric fundus","highlight":true},{"title":"Procedure","content":"Gastric biopsy taken with Sydney protocol"}]'),
('Barrett''s Esophagus', 'UGI', '[{"title":"Esophagus","content":"Tiny mucosal breaks with ulcer at GE junction\nProjection of small reddish velvety mucosa at 35 cm"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I\nPatulous GE junction – Hill class II","highlight":true},{"title":"Stomach","content":"Multiple erosions in gastric antrum"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Erosions+"},{"title":"Impression","content":"Short segment Barrett''s esophagus – Prague class C2 M3\nPatulous GE junction – Hill class II\nAntral gastritis\nDuodenitis","highlight":true},{"title":"Procedure","content":"D2 biopsy taken"}]'),
('Candida Esophagus', 'UGI', '[{"title":"Esophagus","content":"Multiple whitish plaques at 35 cm"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I","highlight":true},{"title":"Stomach","content":"Multiple erosions in gastric antrum"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Esophageal candidiasis\nErosive antral gastritis","highlight":true}]'),
('Carcinoma Esophagus', 'UGI', '[{"title":"Esophagus","content":"Noduloproliferative growth seen at 18 cm and extending up to 23 cm\nBiopsy taken"},{"title":"Advanced Imaging (NBI)","content":"Dilated irregular vessels with amorphous surface – s/o malignancy","highlight":true},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Noduloproliferative growth at upper esophagus – ?Carcinoma Esophagus\nBiopsy taken","highlight":true}]'),
('Carcinoma Post Cricoid', 'UGI', '[{"title":"Esophagus","content":"Ulceroproliferative growth in post cricoid area\nScope not negotiable beyond"},{"title":"Advanced Imaging (NBI)","content":"Dilated irregular vessels with amorphous surface – s/o malignancy","highlight":true},{"title":"Stomach","content":"Not seen"},{"title":"Duodenal Cap","content":"Not seen"},{"title":"IInd Part of Duodenum","content":"Not seen"},{"title":"Impression","content":"Ulceroproliferative growth at post cricoid – ?Ca Post Cricoid","highlight":true},{"title":"Procedure","content":"Biopsy taken"}]'),
('Carcinoma Stomach', 'UGI', '[{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Ulceroproliferative growth in gastric cardia and gastric body extending up to antrum\nScope negotiable beyond"},{"title":"Advanced Imaging (NBI)","content":"Dilated irregular vessels with amorphous surface – s/o malignancy","highlight":true},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Ulceroproliferative growth in stomach – ?Ca Stomach\nBiopsy taken","highlight":true}]'),
('Peptic Stricture', 'UGI', '[{"title":"Esophagus","content":"Stricture at 30 cm\nMucosal breaks at GE junction"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I\nPatulous GE junction – Hill class III","highlight":true},{"title":"Stomach","content":"Multiple erosions in gastric antrum"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Stricture at lower esophagus – Peptic stricture\nChanges of reflux esophagitis\nPatulous GE junction – Hill class III\nAntral gastritis","highlight":true}]'),
('UGI - Dilatation', 'UGI', '[{"title":"Esophagus","content":"Stricture at 35 cm – Peptic stricture\nStricture dilated up to 15 mm with Savary-Gilliard dilator"},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Stricture at lower end of esophagus – Peptic stricture\nStricture dilated up to 15 mm with Savary-Gilliard dilator","highlight":true}]'),
('Esophageal Varices + PHG', 'UGI', '[{"title":"Esophagus","content":"Large long columns of varices with red wale sign"},{"title":"Stomach","content":"Erythematous, edematous, friable mucosa with mosaic pattern"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Grade III esophageal varices\nPortal hypertensive gastropathy","highlight":true}]'),
('Foreign Body', 'UGI', '[{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Foreign body (Rs. 2 coin) in duodenal bulb\nForeign body removed with Roth net basket"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Foreign body (Rs. 2 coin) in duodenal bulb\nForeign body removed with Roth net basket","highlight":true}]'),
('Polypectomy', 'UGI', '[{"title":"Esophagus","content":"Small mucosal break at GE junction\nPatulous GE junction – Hill class I"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I","highlight":true},{"title":"Stomach","content":"Large polyps in gastric body along lesser curvature\nAnother small polyp in gastric body"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Changes of reflux esophagitis\nPatulous GE junction – Hill class I\nLarge gastric polyps – ?Fundic gland polyps","highlight":true},{"title":"Procedure","content":"Polypectomy done"}]'),
('Reflux Esophagitis (LA Grade A)', 'UGI', '[{"title":"Esophagus","content":"Small ulcer at GE junction\nPatulous GE junction – Hill class II"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I","highlight":true},{"title":"Stomach","content":"Multiple erosions in gastric antrum"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Few erosions+"},{"title":"Impression","content":"Mild esophagitis – Los Angeles Grade A\nPatulous GE junction – Hill class II\nAntral gastritis","highlight":true}]'),
('Mallory Weiss Tear', 'UGI', '[{"title":"Esophagus","content":"Large deep mucosal tear and adherent clot at GE junction\nFive hemoclips applied & hemostasis achieved"},{"title":"Stomach","content":"Small hiatus hernia – Hill class IV\nMultiple erosions in gastric antrum"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Large deep Mallory Weiss tear\nHemoclips applied & hemostasis achieved","highlight":true}]'),
('Post Cricoid Foreign Body', 'UGI', '[{"title":"Esophagus","content":"Foreign body (metallic earring) impacted at post cricoid area\nForeign body extracted with rat tooth forcep\nSmall ulcer at foreign body impacted area in post cricoid"},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Impacted foreign body (metallic earring) at post cricoid area\nSmall ulcer at post cricoid area\nForeign body extracted with rat tooth forcep","highlight":true}]'),
('Post Cricoid Dilatation', 'UGI', '[{"title":"DILATATION","content":"","isHeading":true},{"title":"Esophagus","content":"Stricture at post cricoid area\nStricture dilated up to 15mm with Savary-Gilliard dilator"},{"title":"POST DILATATION","content":"","isHeading":true},{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Impression","content":"Post Cricoid Stricture – Plummer Vinson Syndrome\nStricture dilated up to 15mm with Savary-Gilliard dilator","highlight":true}]'),
('Post Cricoid Stricture', 'UGI', '[{"title":"Esophagus","content":"Stricture at post cricoid area\nScope not negotiable beyond"},{"title":"Stomach","content":"Not seen"},{"title":"Duodenal Cap","content":"Not seen"},{"title":"IInd Part of Duodenum","content":"Not seen"},{"title":"Advanced Imaging","content":"BLI screening done","highlight":true},{"title":"Impression","content":"Post cricoid stricture – ?Plummer Vinson syndrome\nAdvice: Dilatation on follow-up","highlight":true}]'),
('Reflux Esophagitis', 'UGI', '[{"title":"Esophagus","content":"Tiny ulcer with mucosal breaks at GE junction\nPatulous GE junction – Hill class I"},{"title":"Advanced Imaging (NBI)","content":"Dilated IPCLs Type I","highlight":true},{"title":"Stomach","content":"Few erosions in antrum of stomach"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Tiny ulcer with mucosal breaks"},{"title":"Impression","content":"Changes of reflux esophagitis\nPatulous GE junction – Hill class I\nMild antral gastritis","highlight":true}]'),
('Normal Study', 'UGI', '[{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Normal"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"Advanced Imaging","content":"NBI screening done","highlight":true},{"title":"Impression","content":"Normal study","highlight":true}]'),
('VLS Scopy – Normal', 'VLS', '[{"title":"Oropharynx","content":"Normal"},{"title":"Vallecula and Epiglottis","content":"Normal"},{"title":"Pyriform Fossa","content":"Normal"},{"title":"Laryngeal Opening","content":"Normal"},{"title":"Advanced Imaging","content":"NBI screening done","highlight":true},{"title":"Impression","content":"Normal VLS Scopy study","highlight":true}]'),
('Normal Study', 'SIGMOIDOSCOPY', '[{"title":"Rectum","content":"Normal"},{"title":"Sigmoid Colon","content":"Normal"},{"title":"Descending Colon","content":"Normal"},{"title":"Advanced Imaging","content":"SPES screening done","highlight":true},{"title":"Impression","content":"Normal sigmoidoscopy study","highlight":true}]'),
('Sigmoid Hemorrhoids', 'SIGMOIDOSCOPY', '[{"title":"Rectum","content":"Small Internal and external Hemorrhoids"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending Colon","content":"Normal"},{"title":"Impression","content":"Small Internal and External Hemorrhoids","highlight":true}]'),
('SRUS', 'SIGMOIDOSCOPY', '[{"title":"Rectum","content":"Small whitebase ulcer with edematous & Erythematous mucosa\nProlapsed mucosa+"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending colon","content":"Normal"},{"title":"Impression","content":"Small ulcer with Prolapsed Rectal mucosa\n-?Solitary Rectal Ulcer Syndrome (S.R.U.S)\nBiopsy Taken","highlight":true}]'),
('Ulcerative Colitis', 'SIGMOIDOSCOPY', '[{"title":"Rectum","content":"Loss of vascular pattern with increased mucosal granularity & friability with Multiple superficial ulcers in Distal Rectum"},{"title":"Sigmoid colon","content":"Loss of vascular pattern with increased mucosal granularity & friability with Multiple superficial ulcers"},{"title":"Descending colon","content":"Normal"},{"title":"Impression","content":"-?Inflamatory Bowel Disease - Ulcerative Colitis\nUCEIS Score – 6/8\nMontreal Classification – E1\n• Biopsy Taken","highlight":true}]'),
('Ampullary adenoma', 'ERCP', '[{"title":"Procedure","content":"Large Bulky protruding Papilla\nSelective CBD Cannulation done\nCholangiogram Showed Dialated IHBR and proximal CBD with Tight short Distal CBD Stricture\nEndoscopic Biliary sphincterotomy done\nBiopsy Taken\n“Uromed” 10fr X 10cm Double pigtail plastic stent placed in CBD\nPus++"},{"title":"Impression","content":"Obstructive Jaundice with Acute Cholangitis\nTight Distal CBD Stricture -? Ampullary adenoma\nUnderwent ERCP with Biliary stenting\n• Biopsy Taken","highlight":true}]'),
('CBD Stent Exchange', 'ERCP', '[{"title":"Procedure","content":"Previous Biliary stent in situ\nRemoved with Rattooth forcep\nCBD cannulated\nPrevious Biliary sphicterotomy present\nCholangiogram Showed - Mildly dialated CBD with mid CBD calculi with distal CBD stricture\nBalloon sweep done,stone could not be retrived due to distal CBD narrowing. 10fr x 7cm DPT plastic stent placed."},{"title":"Impression","content":"Cholelithiasis and Choledocholithiasis\nS/p ERCP with Biliary Stenting Underwent ERCP– CBD stent exchange done","highlight":true}]'),
('CCP PD Stenting', 'ERCP', '[{"title":"Procedure","content":"Narrowing at D1 and D2 junction\nPancreatic duct cannulated via mejor papilla\nPrevious Pancreatic sphincterotomy Extended\nPancreatogram showed Dilated irregular Pancreatic Duct with multiple calculi\nMultiple calculi flushed out\n07 fr X 10cm Single pigtail stent placed in Pancreatic Duct Across the Stricture"},{"title":"Impression","content":"K/C/O Chronic Calcific Pancreatitis\nUnderwent ERCP with Pancreatic duct stent Exchange","highlight":true}]'),
('ERCP CBD Stent', 'ERCP', '[{"title":"Procedure","content":"Selective CBD cannulation done\nCholangiogram Showed – Grossly Dialated CBD with Multiple Large calculi\nEndoscopic Biliary sphincterotomy done\nEndoscopic Large Papillary Balloon Sphincteroplasty done\nBalloon sweep done and CBD cleared – Multiple large Calculi extracted\nBalloon Occlusion Cholangiogram Showed – Normal CBD\n“UROMED’s” 10fr X 10cm Double Pigtail plastic stent placed in CBD"},{"title":"Impression","content":"Obstructive Jaundice with Acute Cholangitis\nCholedocholithiasis\nUnderwent ERCP with CBD clearance and Biliary stenting","highlight":true}]'),
('ERCP Stent Removal', 'ERCP', '[{"title":"Procedure","content":"Previous Biliary stent in situ\nRemoved with Rattooth forcep\nCBD cannulated\nPrevious Biliary sphicterotomy present\nCholangiogram Showed - Mildly dialated CBD with Sludge\nBalloon sweep done and CBD cleared – Sludge extracted\nBalloon Occlusion Cholangiogram Showed – Normal CBD"},{"title":"Impression","content":"C/o Cholelithiasis and Choledocholithiasis\nS/p ERCP with Biliary Stenting F/b Cholecystectomy Underwent ERCP with Biliary Stent removal & CBD clearance","highlight":true}]'),
('Normal Enteroscopy', 'ENTEROSCOPY', '[{"title":"Procedure","content":"Antegrade Enteroscopy done with Single Balloon Enteroscope\nSIF- Q180 & CO2 insufflation under propofol sedation"},{"title":"Esophagus","content":"Normal"},{"title":"Stomach","content":"Multiple erosions in Gastric Body"},{"title":"Duodenal Cap","content":"Normal"},{"title":"IInd Part of Duodenum","content":"Normal"},{"title":"IIIrd Part Of Duodenum","content":"Normal"},{"title":"Jejunum","content":"Normal - Jejunum seen upto 200cm"},{"title":"Impression","content":"Normal Antegrade Enteroscopy\n• Jejunal Biopsies Taken","highlight":true}]'),
('Retrograde Enteroscopy', 'ENTEROSCOPY', '[{"title":"Procedure","content":"Retrograde Enteroscopy done with Single Balloon Enteroscope SIF- Q180 & CO2 insufflation under propofol"},{"title":"Rectum","content":"Normal"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending colon","content":"Normal"},{"title":"Transverse colon","content":"Normal"},{"title":"Ascending colon","content":"Normal"},{"title":"Caecum","content":"Normal"},{"title":"Terminal Ileum","content":"Tight Stricture at Distal Ileum with normal overlying mucosa , Biopsy Taken. Scope could not be Negotiated beyond."},{"title":"Impression","content":"Tight Stricture with Ulcer In Distal Ileum ? Inflammetory Bowel Disease – Chron’s Disease\nBiopsy Taken","highlight":true}]'),
('Argon Plasma Coagulation', 'COLONOSCOPY', '[{"title":"ARGON PLASMA COAGULATION","isHeading":true},{"title":"Rectum","content":"Large whitebase ulcer with Mucosal Edema & erythema\nProlaps mucosa+\nArgon Plasma Coagulation Done"},{"title":"Sigmoid colon To Caecum","content":"Normal"},{"title":"Terminal Ileum","content":"Normal, Ileum seen upto 30cm"},{"title":"Des","content":""},{"title":"Impression","content":"K/c/o Solitary Rectal Ulcer Syndrome\nArgon Plasma Coagulation Done for S.R.U.S","highlight":true}]'),
('Colon Growth', 'COLONOSCOPY', '[{"title":"Rectum","content":"Normal"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending colon","content":"Normal"},{"title":"Transeverse colon","content":"Circumferential Ulceroproliferative growth significant luminal narrowing\nAdvanced imaging (NBI Image) Dialated irregular vessals with amorphous surface with s/o Malignancy\nScope not negotiable beyond"},{"title":"Ascending colon","content":"Not seen"},{"title":"Caecum","content":"Not seen"},{"title":"Terminal ileum","content":"Not seen"},{"title":"Advance Imaging","content":"NBI screening done"},{"title":"Impression","content":"Ulceroproliferative growth in Transeverse Colon -? Ca Transeverse Colon\n– Biopsy taken","highlight":true}]'),
('Normal Colonoscopy', 'COLONOSCOPY', '[{"title":"Rectum","content":"Normal"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending colon","content":"Normal"},{"title":"Transeverse colon","content":"Normal"},{"title":"Ascending colon","content":"Normal"},{"title":"Caecum","content":"Normal"},{"title":"Terminal ileum","content":"Normal"},{"title":"Impression","content":"Normal study","highlight":true}]'),
('Polyp', 'COLONOSCOPY', '[{"title":"Rectum","content":"Normal"},{"title":"Sigmoid colon","content":"Small Polyp at Sigmoid – Descending junction"},{"title":"Descending colon","content":"Small Polyp"},{"title":"Transeverse colon","content":"Normal"},{"title":"Ascending colon","content":"Normal"},{"title":"Caecum","content":"Normal"},{"title":"Terminal ileum","content":"Normal, Ileum seen upto 30cm"},{"title":"Impression","content":"Small Polyps in Sigmoid colon & Desecending colon\n• Advice :- Polypectomy","highlight":true}]'),
('Terminal Ileum Ulcer', 'COLONOSCOPY', '[{"title":"Rectum","content":"Normal"},{"title":"Sigmoid colon","content":"Normal"},{"title":"Descending colon","content":"Normal"},{"title":"Transeverse colon","content":"Normal"},{"title":"Ascending colon","content":"Normal"},{"title":"Caecum","content":"Normal"},{"title":"Terminal ileum","content":"superficeal ulcers, Ileum seen upto 30cm"},{"title":"Impression","content":"superfeceal ulcers in Terminal ileum ? infective\n- Ileal Biopsy Taken","highlight":true}]'),
('Ulcerative Colitis', 'COLONOSCOPY', '[{"title":"Rectum","content":"Loss of vascular pattern with edematous & erythematous mucosa with increased mucosal granularity and Friability"},{"title":"Sigmoid colon","content":"Loss of vascular pattern with edematous & erythematous mucosa with increased mucosal granularity and Friability"},{"title":"Descending colon","content":"Normal"},{"title":"Transeverse colon","content":"Normal"},{"title":"Ascending colon","content":"Normal"},{"title":"Caecum","content":"Normal, Poor Preparation"},{"title":"Terminal ileum","content":"Normal, Ileum Seen upto 30cm"},{"title":"Impression","content":"-?Inflamatory Bowel Disease - Ulcerative Colitis\nUCEIS Score – 6/8\nMontreal Classification – E2\n• Biopsy Taken","highlight":true}]');


CREATE TABLE IF NOT EXISTS settings (
  key TEXT PRIMARY KEY,
  value TEXT
);

-- Default settings (INSERT OR IGNORE = don't overwrite if already set)
INSERT OR IGNORE INTO settings (key, value) VALUES ('report_prefix', 'SH');
INSERT OR IGNORE INTO settings (key, value) VALUES ('last_backup_date', NULL);
INSERT OR IGNORE INTO settings (key, value) VALUES ('auto_backup_enabled', '1');

-- Add new columns to existing reports table if upgrading
-- We run these via try-catch in JS to avoid breaking the script.

CREATE TABLE IF NOT EXISTS disease_dictionary (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  category TEXT,
  keywords TEXT -- JSON array
);

CREATE TABLE IF NOT EXISTS organ_dictionary (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT UNIQUE NOT NULL,
  keywords TEXT -- JSON array
);

CREATE TABLE IF NOT EXISTS report_diseases (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  report_id INTEGER REFERENCES reports(id) ON DELETE CASCADE,
  patient_id INTEGER REFERENCES patients(id) ON DELETE CASCADE,
  disease_name TEXT,
  organ_name TEXT,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);

-- Seed basic dictionaries
INSERT OR IGNORE INTO disease_dictionary (name, category, keywords) VALUES
('Gastritis', 'Inflammation', '["gastritis", "antral gastritis", "pangastritis", "erythema"]'),
('Ulcer', 'Ulcer', '["ulcer", "ulceration", "ulcers"]'),
('Cancer', 'Malignancy', '["cancer", "ca ", "carcinoma", "malignancy", "malignant", "tumor", "growth"]'),
('Esophagitis', 'Inflammation', '["esophagitis", "lax les"]'),
('Barrett''s Esophagus', 'Pre-malignant', '["barrett", "barrett''s"]'),
('Hiatus Hernia', 'Structural', '["hiatus hernia", "hiatal hernia"]'),
('GERD', 'Reflux', '["gerd", "reflux"]'),
('Varices', 'Vascular', '["varices", "varix"]'),
('Portal Hypertensive Gastropathy', 'Vascular', '["phg", "portal hypertensive gastropathy"]'),
('Polyps', 'Structural', '["polyp", "polyps", "polypoid"]'),
('Hemorrhoids', 'Vascular', '["hemorrhoids", "piles"]'),
('Colitis', 'Inflammation', '["colitis", "ulcerative colitis", "crohn", "ibd"]'),
('Celiac Disease', 'Autoimmune', '["celiac", "coeliac"]'),
('Strictures', 'Structural', '["stricture", "stenosis", "narrowing"]'),
('Diverticulosis', 'Structural', '["diverticulosis", "diverticula", "diverticulum"]');

INSERT OR IGNORE INTO organ_dictionary (name, keywords) VALUES
('Esophagus', '["esophagus", "esophageal", "lower esophagus", "upper esophagus", "ge junction", "z-line"]'),
('Stomach', '["stomach", "gastric", "antrum", "body", "fundus", "pylorus", "incisura"]'),
('Duodenum', '["duodenum", "duodenal", "d1", "d2", "d3", "bulb"]'),
('Small Intestine', '["jejunum", "ileum", "small bowel", "small intestine"]'),
('Colon', '["colon", "ascending colon", "transverse colon", "descending colon", "sigmoid", "caecum", "cecum", "large intestine"]'),
('Rectum', '["rectum", "rectal"]');

CREATE TABLE IF NOT EXISTS users (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  username TEXT UNIQUE NOT NULL,
  password_hash TEXT NOT NULL,
  salt TEXT NOT NULL,
  role TEXT DEFAULT 'user',
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
);